[tool]
[tool.poetry]
name = "app_tensorflow"
version = "0.0.1"
description = ""
authors = ["Crystal Widjaja <you@example.com>"]
[tool.poetry.dependencies]
python = "^3.8.5"
flask = "^1.1.2"
Pillow = "^7.2.0"
tensorflow = "^2.3.0"
